use frescos;
insert into warehouse values (null, "cd_meli_01_sp");
insert into warehouse values (null, "cd_meli_01_sc");
insert into warehouse values (null, "cd_meli_01_pr");
insert into warehouse values (null, "cd_meli_01_rj");
insert into warehouse values (null, "cd_meli_01_es");
insert into warehouse values (null, "cd_meli_01_df");

insert into section values (null, "FRESH", 5000.0, 5000.0, 1);
insert into section values (null, "REFRIGERATED", 5000.0, 5000.0, 1);
insert into section values (null, "FROZEN", 5000.0, 5000.0, 1);

insert into product values (null, "FRESH", "rucula", 0.1);
insert into product values (null, "REFRIGERATED", "mozzarela de bufala", 0.5);
insert into product values (null, "FROZEN", "pernil suino", 0.6);
insert into product values (null, "FRESH", "alface", 0.1);
insert into product values (null, "REFRIGERATED", "queijo do reino", 0.5);
insert into product values (null, "FROZEN", "frango", 0.6);
insert into product values (null, "FRESH", "agrião", 0.1);
insert into product values (null, "REFRIGERATED", "queijo parmesão", 0.5);
insert into product values (null, "FROZEN", "coxão mole", 0.6);
insert into product values (null, "FRESH", "catalonia", 0.1);
insert into product values (null, "REFRIGERATED", "mortadela", 0.5);
insert into product values (null, "FROZEN", "bisteca suína", 0.6);
insert into product values (null, "FRESH", "espinafre", 0.1);
insert into product values (null, "REFRIGERATED", "presunto parma", 0.5);
insert into product values (null, "FROZEN", "rabada", 0.6);
insert into product values (null, "FRESH", "alecrim", 0.1);
insert into product values (null, "REFRIGERATED", "quejo prato", 0.5);
insert into product values (null, "FROZEN", "costela bovina", 0.6);
insert into product values (null, "FRESH", "manjericão", 0.1);
insert into product values (null, "REFRIGERATED", "azeitona", 0.5);
insert into product values (null, "FROZEN", "lombinho", 0.6);
insert into product values (null, "FRESH", "acelga", 0.1);
insert into product values (null, "REFRIGERATED", "champingnon", 0.5);
insert into product values (null, "FROZEN", "picanha", 0.6);
insert into product values (null, "FRESH", "brócolis", 0.1);
insert into product values (null, "REFRIGERATED", "presunto", 0.5);
insert into product values (null, "FROZEN", "alcatra", 0.6);
insert into product values (null, "FRESH", "couve flor", 0.1);
insert into product values (null, "REFRIGERATED", "cheddar", 0.5);
insert into product values (null, "FROZEN", "patinho", 0.6);
insert into product values (null, "FRESH", "hortelã", 0.1);
insert into product values (null, "REFRIGERATED", "requeijão", 0.5);
insert into product values (null, "FROZEN", "lagarto", 0.6);
insert into product values (null, "FRESH", "estragão francês", 0.1);
insert into product values (null, "REFRIGERATED", "iogurte", 0.5);
insert into product values (null, "FROZEN", "paleta", 0.6);
insert into product values (null, "FRESH", "orégano", 0.1);
insert into product values (null, "REFRIGERATED", "queijo brie", 0.5);
insert into product values (null, "FROZEN", "fraldinha", 0.6);

insert into seller values (null, "Raul");
insert into seller values (null, "Bon Jovi");
insert into seller values (null, "Eddy");
insert into seller values (null, "Mulher Maravilha");
insert into seller values (null, "Nando Reis");
insert into seller values (null, "Cássia Eller");

insert into agent values (null, "Armandinho", 1);
insert into agent values (null, "Bowie", 2);
insert into agent values (null, "Wonder Woman", 3);
insert into agent values (null, "Paul", 4);
insert into agent values (null, "Bruce", 5);
insert into agent values (null, "Rita Lee", 6);

insert into buyer values(null, "Panqueca");
insert into buyer values(null, "Otto");
insert into buyer values(null, "Betânia");
insert into buyer values(null, "Gal");
insert into buyer values(null, "Yoshi");
insert into buyer values(null, "Lisa");
insert into buyer values(null, "Bela");
insert into buyer values(null, "Tony");
insert into buyer values(null, "Mérion");
insert into buyer values(null, "Sofia");
insert into buyer values(null, "Eros");
insert into buyer values(null, "Jana");

insert into adsense values (null, 10.99, 1, 1);
insert into adsense values (null, 79.99, 2, 1);
insert into adsense values (null, 15.99, 3, 1);
insert into adsense values (null, 15.99, 4, 1);
insert into adsense values (null, 15.99, 5, 1);
insert into adsense values (null, 15.99, 6, 1);
insert into adsense values (null, 15.99, 7, 1);
insert into adsense values (null, 15.99, 8, 1);
insert into adsense values (null, 15.99, 9, 1);
insert into adsense values (null, 15.99, 10, 1);
insert into adsense values (null, 15.99, 11, 1);
insert into adsense values (null, 15.99, 12, 1);
insert into adsense values (null, 15.99, 13, 1);
insert into adsense values (null, 15.99, 14, 1);
insert into adsense values (null, 15.99, 15, 1);
insert into adsense values (null, 15.99, 16, 1);
insert into adsense values (null, 15.99, 17, 1);
insert into adsense values (null, 15.99, 18, 1);
insert into adsense values (null, 15.99, 19, 1);
insert into adsense values (null, 15.99, 20, 1);
insert into adsense values (null, 15.99, 21, 1);
insert into adsense values (null, 15.99, 22, 1);
insert into adsense values (null, 15.99, 23, 1);
insert into adsense values (null, 15.99, 24, 1);
insert into adsense values (null, 15.99, 25, 1);
insert into adsense values (null, 15.99, 26, 1);
insert into adsense values (null, 15.99, 27, 1);
insert into adsense values (null, 15.99, 28, 1);
insert into adsense values (null, 15.99, 29, 1);
insert into adsense values (null, 15.99, 30, 1);
insert into adsense values (null, 15.99, 31, 1);
insert into adsense values (null, 15.99, 32, 1);
insert into adsense values (null, 15.99, 33, 1);
insert into adsense values (null, 15.99, 34, 1);
insert into adsense values (null, 15.99, 35, 1);
insert into adsense values (null, 15.99, 36, 1);
insert into adsense values (null, 15.99, 37, 1);
insert into adsense values (null, 15.99, 38, 1);
insert into adsense values (null, 15.99, 39, 1);

insert into section values (null, "FRESH", 500.0, 500.0, 2);
insert into section values (null, "REFRIGERATED", 500.0, 500.0, 2);
insert into section values (null, "FROZEN", 500.0, 500.0, 2);
